In [1]:
import xarray as xr
print('Xarray version', xr.__version__)

Xarray version 2025.6.1


# Example of one netCDF file with xarray

In [2]:
# ds = xr.open_dataset("train/v3.LR.DTESTM.pm-cpu-10yr.mpassi.hist.am.timeSeriesStatsDaily.0010-01-01.nc")

from perlmutterpath import * # has the path to the data on Perlmutter
ds = xr.open_dataset(full_data_dir_sample, decode_times=True)

In [3]:
ds.data_vars

Data variables:
    timeDaily_counter             (Time) int32 124B ...
    xtime_startDaily              (Time) |S64 2kB ...
    xtime_endDaily                (Time) |S64 2kB ...
    timeDaily_avg_iceAreaCell     (Time, nCells) float32 58MB ...
    timeDaily_avg_iceVolumeCell   (Time, nCells) float32 58MB ...
    timeDaily_avg_snowVolumeCell  (Time, nCells) float32 58MB ...
    timeDaily_avg_uVelocityGeo    (Time, nVertices) float32 117MB ...
    timeDaily_avg_vVelocityGeo    (Time, nVertices) float32 117MB ...

In [4]:
day_counter = ds["timeDaily_counter"].shape[0]
print(day_counter)

31


In [5]:
print(ds["xtime_startDaily"])

<xarray.DataArray 'xtime_startDaily' (Time: 31)> Size: 2kB
[31 values with dtype=|S64]
Dimensions without coordinates: Time


In [6]:
print(ds["xtime_startDaily"].values)

[b'2024-12-01_00:00:00' b'2024-12-02_00:00:00' b'2024-12-03_00:00:00'
 b'2024-12-04_00:00:00' b'2024-12-05_00:00:00' b'2024-12-06_00:00:00'
 b'2024-12-07_00:00:00' b'2024-12-08_00:00:00' b'2024-12-09_00:00:00'
 b'2024-12-10_00:00:00' b'2024-12-11_00:00:00' b'2024-12-12_00:00:00'
 b'2024-12-13_00:00:00' b'2024-12-14_00:00:00' b'2024-12-15_00:00:00'
 b'2024-12-16_00:00:00' b'2024-12-17_00:00:00' b'2024-12-18_00:00:00'
 b'2024-12-19_00:00:00' b'2024-12-20_00:00:00' b'2024-12-21_00:00:00'
 b'2024-12-22_00:00:00' b'2024-12-23_00:00:00' b'2024-12-24_00:00:00'
 b'2024-12-25_00:00:00' b'2024-12-26_00:00:00' b'2024-12-27_00:00:00'
 b'2024-12-28_00:00:00' b'2024-12-29_00:00:00' b'2024-12-30_00:00:00'
 b'2024-12-31_00:00:00']


In [7]:
ice_area = ds["timeDaily_avg_iceAreaCell"]
print(ds['timeDaily_avg_iceAreaCell'].attrs['long_name'])
print(f"Shape of ice area variable: {ice_area.shape}")

Fraction of grid cell covered in sea ice
Shape of ice area variable: (31, 465044)


In [8]:
ice_volume = ds["timeDaily_avg_iceVolumeCell"]
print(ds['timeDaily_avg_iceVolumeCell'].attrs['long_name'])
print(f"Shape of ice area variable: {ice_volume.shape}")

Ice volume per unit area of grid cell
Shape of ice area variable: (31, 465044)


In [9]:
print(ds.coords)
print(ds.dims)

Coordinates:
    *empty*
FrozenMappingWarningOnValuesAccess({'Time': 31, 'nCells': 465044, 'nVertices': 942873})


In [10]:
print(ds)
ds.close()

<xarray.Dataset> Size: 407MB
Dimensions:                       (Time: 31, nCells: 465044, nVertices: 942873)
Dimensions without coordinates: Time, nCells, nVertices
Data variables:
    timeDaily_counter             (Time) int32 124B ...
    xtime_startDaily              (Time) |S64 2kB b'2024-12-01_00:00:00' ... ...
    xtime_endDaily                (Time) |S64 2kB ...
    timeDaily_avg_iceAreaCell     (Time, nCells) float32 58MB ...
    timeDaily_avg_iceVolumeCell   (Time, nCells) float32 58MB ...
    timeDaily_avg_snowVolumeCell  (Time, nCells) float32 58MB ...
    timeDaily_avg_uVelocityGeo    (Time, nVertices) float32 117MB ...
    timeDaily_avg_vVelocityGeo    (Time, nVertices) float32 117MB ...
Attributes: (12/490)
    case:                                                         v3.LR.histo...
    source_id:                                                    399d430113
    realm:                                                        seaIce
    product:                          

# Example of Mesh File

In [11]:
mesh = xr.open_dataset("NC_FILE_PROCESSING/mpassi.IcoswISC30E3r5.20231120.nc")

In [12]:
mesh.data_vars

Data variables:
    edgesOnEdge        (nEdges, maxEdges2) int32 68MB ...
    weightsOnEdge      (nEdges, maxEdges2) float64 135MB ...
    cellsOnEdge        (nEdges, TWO) int32 11MB ...
    verticesOnEdge     (nEdges, TWO) int32 11MB ...
    angleEdge          (nEdges) float64 11MB ...
    dcEdge             (nEdges) float64 11MB ...
    dvEdge             (nEdges) float64 11MB ...
    indexToEdgeID      (nEdges) int32 6MB ...
    latEdge            (nEdges) float64 11MB ...
    lonEdge            (nEdges) float64 11MB ...
    nEdgesOnEdge       (nEdges) int32 6MB ...
    xEdge              (nEdges) float64 11MB ...
    yEdge              (nEdges) float64 11MB ...
    zEdge              (nEdges) float64 11MB ...
    fEdge              (nEdges) float64 11MB ...
    cellsOnVertex      (nVertices, vertexDegree) int32 11MB ...
    edgesOnVertex      (nVertices, vertexDegree) int32 11MB ...
    kiteAreasOnVertex  (nVertices, vertexDegree) float64 23MB ...
    areaTriangle       (nVertices)

In [13]:
print(mesh["latCell"].attrs['long_name'])
print(mesh["lonCell"].attrs['long_name'])

Latitude location of cell centers in radians.
Longitude location of cell centers in radians.


In [14]:
cellsOnCell = mesh["cellsOnCell"].values
print(mesh["cellsOnCell"].attrs['long_name'])
print(mesh["cellsOnCell"].values)

List of cells that neighbor each cell.
[[     5      4      0      0      0      0]
 [    12     11      9      8      0      3]
 [     4     13     12      2      0      0]
 ...
 [465043      0 465040 465041      0      0]
 [     0 465042      0 465044      0      0]
 [     0      0      0      0 465043      0]]


In [15]:
print(cellsOnCell.shape[1])

6


In [16]:
print(mesh["cellsOnCell"].max().values)
print(mesh["cellsOnCell"].min().values)

465044
0


In [28]:
cellAreas = mesh["areaCell"].values
print(mesh["areaCell"].attrs['long_name'])
print(mesh["areaCell"].values)

cellAreas_units = mesh['areaCell'].attrs.get('units')
print(f"Units of area: {cellAreas_units}")

Area of each cell in the primary grid.
[7.23558958e+08 7.25959862e+08 7.24416211e+08 ... 7.85442411e+08
 7.85841763e+08 7.86602452e+08]
Units of area: m^2


In [32]:
import numpy as np

latCell = np.degrees(mesh["latCell"].values)
latitude_threshold = 40

print(latCell.shape)

mask = latCell >= latitude_threshold
print(mask.shape)
print(cellAreas.shape)

masked_cellAreas = cellAreas[mask]

square_kilometers_total = sum(masked_cellAreas) // 1e+6 # meters square converted to kilometers square

print(square_kilometers_total)

(465044,)
(465044,)
(465044,)
42069840.0


In [ ]:
#np.save('cellsOnCell.npy', cellsOnCell) 
#np.save('cellAreas.npy', cellAreas) 

In [ ]:
#landIceMask = mesh["landIceMask"].values
#np.save('landIceMask.npy', landIceMask)

In [ ]:
print(mesh.coords)
print(mesh.dims)

In [ ]:
print(mesh)

In [ ]:
mesh.close()