In [3]:
import xarray as xr
print('Xarray version', xr.__version__)

Xarray version 2025.6.1


In [11]:
from perlmutterpath import * # has the path to the data on Perlmutter
ds_fluxes = xr.open_dataset(full_data_fluxes_mean_sample, decode_times=True)

In [12]:
print(ds_fluxes)

<xarray.Dataset> Size: 48MB
Dimensions:                                           (nCells: 465044,
                                                       nVertices: 942873)
Dimensions without coordinates: nCells, nVertices
Data variables: (12/24)
    timeMonthly_avg_absorbedShortwaveFluxInitialArea  (nCells) float32 2MB ...
    timeMonthly_avg_basalIceMelt                      (nCells) float32 2MB ...
    timeMonthly_avg_congelation                       (nCells) float32 2MB ...
    timeMonthly_avg_divergence                        (nCells) float32 2MB ...
    timeMonthly_avg_frazilFormation                   (nCells) float32 2MB ...
    timeMonthly_avg_freezingMeltingPotential          (nCells) float32 2MB ...
    ...                                                ...
    timeMonthly_avg_snowMelt                          (nCells) float32 2MB ...
    timeMonthly_avg_snowVolumeCell                    (nCells) float32 2MB ...
    timeMonthly_avg_snowiceFormation                  (nCells)

In [13]:
ds_fluxes.data_vars

Data variables:
    timeMonthly_avg_absorbedShortwaveFluxInitialArea  (nCells) float32 2MB ...
    timeMonthly_avg_basalIceMelt                      (nCells) float32 2MB ...
    timeMonthly_avg_congelation                       (nCells) float32 2MB ...
    timeMonthly_avg_divergence                        (nCells) float32 2MB ...
    timeMonthly_avg_frazilFormation                   (nCells) float32 2MB ...
    timeMonthly_avg_freezingMeltingPotential          (nCells) float32 2MB ...
    timeMonthly_avg_iceAreaCell                       (nCells) float32 2MB ...
    timeMonthly_avg_iceVolumeCell                     (nCells) float32 2MB ...
    timeMonthly_avg_latentHeatFluxInitialArea         (nCells) float32 2MB ...
    timeMonthly_avg_lateralIceMelt                    (nCells) float32 2MB ...
    timeMonthly_avg_longwaveDown                      (nCells) float32 2MB ...
    timeMonthly_avg_longwaveUpInitialArea             (nCells) float32 2MB ...
    timeMonthly_avg_oceanHeatFlux   

In [14]:
ds_fluxes.close()

# Example of Ocean Heat

In [19]:
from perlmutterpath import * # has the path to the data on Perlmutter
ds_ocean_heat = xr.open_dataset(full_data_ocean_heat_sample, decode_times=True)

In [20]:
print(ds_ocean_heat)

<xarray.Dataset> Size: 7MB
Dimensions:                      (Time: 1, nCells: 465044)
Dimensions without coordinates: Time, nCells
Data variables:
    xtime                        (Time) |S64 64B ...
    oceanHeatContentSfcToBot     (Time, nCells) float32 2MB ...
    oceanHeatContentSfcTo700m    (Time, nCells) float32 2MB ...
    oceanHeatContent700mTo2000m  (Time, nCells) float32 2MB ...
    oceanHeatContent2000mToBot   (Time, nCells) float32 2MB ...
Attributes: (12/816)
    title:                                                        MPAS-Ocean ...
    source:                                                       MPAS Ocean
    source_id:                                                    399d430113
    product:                                                      model-output
    realm:                                                        ocean
    case:                                                         v3.LR.histo...
    ...                                                 

In [21]:
ds_ocean_heat.data_vars

Data variables:
    xtime                        (Time) |S64 64B ...
    oceanHeatContentSfcToBot     (Time, nCells) float32 2MB ...
    oceanHeatContentSfcTo700m    (Time, nCells) float32 2MB ...
    oceanHeatContent700mTo2000m  (Time, nCells) float32 2MB ...
    oceanHeatContent2000mToBot   (Time, nCells) float32 2MB ...

In [27]:
print(ds_ocean_heat["xtime"].values)

[b'1981-07-01_00:00:00']


In [22]:
ds_ocean_heat.close()

# Example of a Regional Statistics File
There is one of these files per month between 1850 and 2024

In [32]:
from perlmutterpath import * # has the path to the data on Perlmutter
ds_regional_stats = xr.open_dataset(full_data_regional_stats_sample, decode_timedelta=True)

In [24]:
print(ds_regional_stats)

<xarray.Dataset> Size: 9kB
Dimensions:              (Time: 31, nRegions: 3)
Dimensions without coordinates: Time, nRegions
Data variables:
    xtime                (Time) |S64 2kB ...
    daysSinceStartOfSim  (Time) timedelta64[ns] 248B ...
    totalIceArea         (Time, nRegions) float64 744B ...
    totalIceExtent       (Time, nRegions) float64 744B ...
    totalIceVolume       (Time, nRegions) float64 744B ...
    totalSnowVolume      (Time, nRegions) float64 744B ...
    totalKineticEnergy   (Time, nRegions) float64 744B ...
    rmsIceSpeed          (Time, nRegions) float64 744B ...
    averageAlbedo        (Time, nRegions) float64 744B ...
    maximumIceVolume     (Time, nRegions) float64 744B ...
    maximumIcePressure   (Time, nRegions) float64 744B ...
Attributes: (12/490)
    case:                                                         v3.LR.histo...
    source_id:                                                    399d430113
    realm:                                       

In [25]:
ds_regional_stats.data_vars

Data variables:
    xtime                (Time) |S64 2kB ...
    daysSinceStartOfSim  (Time) timedelta64[ns] 248B ...
    totalIceArea         (Time, nRegions) float64 744B ...
    totalIceExtent       (Time, nRegions) float64 744B ...
    totalIceVolume       (Time, nRegions) float64 744B ...
    totalSnowVolume      (Time, nRegions) float64 744B ...
    totalKineticEnergy   (Time, nRegions) float64 744B ...
    rmsIceSpeed          (Time, nRegions) float64 744B ...
    averageAlbedo        (Time, nRegions) float64 744B ...
    maximumIceVolume     (Time, nRegions) float64 744B ...
    maximumIcePressure   (Time, nRegions) float64 744B ...

In [29]:
print(ds_regional_stats["xtime"].values)

[b'1950-03-01_00:00:00' b'1950-03-02_00:00:00' b'1950-03-03_00:00:00'
 b'1950-03-04_00:00:00' b'1950-03-05_00:00:00' b'1950-03-06_00:00:00'
 b'1950-03-07_00:00:00' b'1950-03-08_00:00:00' b'1950-03-09_00:00:00'
 b'1950-03-10_00:00:00' b'1950-03-11_00:00:00' b'1950-03-12_00:00:00'
 b'1950-03-13_00:00:00' b'1950-03-14_00:00:00' b'1950-03-15_00:00:00'
 b'1950-03-16_00:00:00' b'1950-03-17_00:00:00' b'1950-03-18_00:00:00'
 b'1950-03-19_00:00:00' b'1950-03-20_00:00:00' b'1950-03-21_00:00:00'
 b'1950-03-22_00:00:00' b'1950-03-23_00:00:00' b'1950-03-24_00:00:00'
 b'1950-03-25_00:00:00' b'1950-03-26_00:00:00' b'1950-03-27_00:00:00'
 b'1950-03-28_00:00:00' b'1950-03-29_00:00:00' b'1950-03-30_00:00:00'
 b'1950-03-31_00:00:00']


In [36]:
print("Ice Area", ds_regional_stats["totalIceArea"].values[0])
print("Ice Extent", ds_regional_stats["totalIceExtent"].values[0])

print(ds_regional_stats['totalIceArea'].attrs)
print(ds_regional_stats['totalIceExtent'].attrs)
print(ds_regional_stats['totalIceVolume'].attrs)
print(ds_regional_stats['totalSnowVolume'].attrs)

Ice Area [18025780.03375199 15845921.9470876   2179858.08666439]
Ice Extent [19881354.41282971 16587617.80059649  3293736.61223322]
{'units': 'km2', 'long_name': 'Total sea-ice area by region'}
{'units': 'km2', 'long_name': 'Total sea-ice extent by region'}
{'units': 'km3', 'long_name': 'Total sea-ice volume by region'}
{'units': 'km3', 'long_name': 'Total snow volume by region'}


In [39]:
# What are the 3 regions?
world = 15845921.9470876 + 2179858.08666439
print(world) # This confirms that the first value is for the globe, while the 2nd and 3rd are hemispheres

# 3 regions: global, northern hemisphere and southern hemisphere.
# https://github.com/E3SM-Project/E3SM/blob/master/components/mpas-seaice/src/analysis_members/mpas_seaice_regional_statistics.F

18025780.03375199


In [26]:
ds_regional_stats.close()

# Example of a Monthly netCDF file with xarray

In [4]:
from perlmutterpath import * # has the path to the data on Perlmutter
ds_monthly = xr.open_dataset(full_data_dir_monthly_sample, decode_timedelta=True)

In [10]:
print(ds_monthly)

<xarray.Dataset> Size: 199MB
Dimensions:                                           (Time: 1, nCells: 465044,
                                                       nCategories: 5, ONE: 1,
                                                       nVertices: 942873,
                                                       maxEdges: 6,
                                                       nSnowLayers: 5)
Dimensions without coordinates: Time, nCells, nCategories, ONE, nVertices,
                                maxEdges, nSnowLayers
Data variables: (12/67)
    timeMonthly_counter                               (Time) int32 4B ...
    xtime_startMonthly                                (Time) |S64 64B b'2024-...
    xtime_endMonthly                                  (Time) |S64 64B ...
    timeMonthly_avg_daysSinceStartOfSim               (Time) timedelta64[ns] 8B ...
    timeMonthly_avg_icePresent                        (Time, nCells) float32 2MB ...
    timeMonthly_avg_iceAreaCategory             

In [5]:
ds_monthly.data_vars

Data variables:
    timeMonthly_counter                               (Time) int32 4B ...
    xtime_startMonthly                                (Time) |S64 64B ...
    xtime_endMonthly                                  (Time) |S64 64B ...
    timeMonthly_avg_daysSinceStartOfSim               (Time) timedelta64[ns] 8B ...
    timeMonthly_avg_icePresent                        (Time, nCells) float32 2MB ...
    timeMonthly_avg_iceAreaCategory                   (Time, nCells, nCategories, ONE) float32 9MB ...
    timeMonthly_avg_iceVolumeCategory                 (Time, nCells, nCategories, ONE) float32 9MB ...
    timeMonthly_avg_snowVolumeCategory                (Time, nCells, nCategories, ONE) float32 9MB ...
    timeMonthly_avg_iceAreaCell                       (Time, nCells) float32 2MB ...
    timeMonthly_avg_iceVolumeCell                     (Time, nCells) float32 2MB ...
    timeMonthly_avg_snowVolumeCell                    (Time, nCells) float32 2MB ...
    timeMonthly_avg_surfaceTe

In [6]:
monthly_counter = ds_monthly["timeMonthly_counter"].shape[0]
print(monthly_counter)

1


In [7]:
print(ds_monthly["xtime_startMonthly"].values)

[b'2024-11-01_00:30:00']


In [8]:
ice_area_monthly = ds_monthly["timeMonthly_avg_iceAreaCell"]
print(ds_monthly['timeMonthly_avg_iceAreaCell'].attrs['long_name'])
print(f"Shape of ice area variable: {ice_area_monthly.shape}")

Fraction of grid cell covered in sea ice
Shape of ice area variable: (1, 465044)


In [9]:
print(ds_monthly['timeMonthly_avg_iceAreaCell'].attrs['long_name'])
print(ds_monthly['timeMonthly_avg_iceAreaCategory'].attrs['long_name'])

Fraction of grid cell covered in sea ice
Fraction of grid cell covered in sea ice per ice thickness category


In [ ]:
ds_monthly.close()

# Example of a Daily netCDF file with xarray

In [2]:
# ds = xr.open_dataset("train/v3.LR.DTESTM.pm-cpu-10yr.mpassi.hist.am.timeSeriesStatsDaily.0010-01-01.nc")

from perlmutterpath import * # has the path to the data on Perlmutter
ds = xr.open_dataset(full_data_dir_sample, decode_times=True)

In [3]:
ds.data_vars

Data variables:
    timeDaily_counter             (Time) int32 124B ...
    xtime_startDaily              (Time) |S64 2kB ...
    xtime_endDaily                (Time) |S64 2kB ...
    timeDaily_avg_iceAreaCell     (Time, nCells) float32 58MB ...
    timeDaily_avg_iceVolumeCell   (Time, nCells) float32 58MB ...
    timeDaily_avg_snowVolumeCell  (Time, nCells) float32 58MB ...
    timeDaily_avg_uVelocityGeo    (Time, nVertices) float32 117MB ...
    timeDaily_avg_vVelocityGeo    (Time, nVertices) float32 117MB ...

In [4]:
day_counter = ds["timeDaily_counter"].shape[0]
print(day_counter)

31


In [5]:
print(ds["xtime_startDaily"])

<xarray.DataArray 'xtime_startDaily' (Time: 31)> Size: 2kB
[31 values with dtype=|S64]
Dimensions without coordinates: Time


In [6]:
print(ds["xtime_startDaily"].values)

[b'2024-12-01_00:00:00' b'2024-12-02_00:00:00' b'2024-12-03_00:00:00'
 b'2024-12-04_00:00:00' b'2024-12-05_00:00:00' b'2024-12-06_00:00:00'
 b'2024-12-07_00:00:00' b'2024-12-08_00:00:00' b'2024-12-09_00:00:00'
 b'2024-12-10_00:00:00' b'2024-12-11_00:00:00' b'2024-12-12_00:00:00'
 b'2024-12-13_00:00:00' b'2024-12-14_00:00:00' b'2024-12-15_00:00:00'
 b'2024-12-16_00:00:00' b'2024-12-17_00:00:00' b'2024-12-18_00:00:00'
 b'2024-12-19_00:00:00' b'2024-12-20_00:00:00' b'2024-12-21_00:00:00'
 b'2024-12-22_00:00:00' b'2024-12-23_00:00:00' b'2024-12-24_00:00:00'
 b'2024-12-25_00:00:00' b'2024-12-26_00:00:00' b'2024-12-27_00:00:00'
 b'2024-12-28_00:00:00' b'2024-12-29_00:00:00' b'2024-12-30_00:00:00'
 b'2024-12-31_00:00:00']


In [7]:
ice_area = ds["timeDaily_avg_iceAreaCell"]
print(ds['timeDaily_avg_iceAreaCell'].attrs['long_name'])
print(f"Shape of ice area variable: {ice_area.shape}")

Fraction of grid cell covered in sea ice
Shape of ice area variable: (31, 465044)


In [8]:
ice_volume = ds["timeDaily_avg_iceVolumeCell"]
print(ds['timeDaily_avg_iceVolumeCell'].attrs['long_name'])
print(f"Shape of ice area variable: {ice_volume.shape}")

Ice volume per unit area of grid cell
Shape of ice area variable: (31, 465044)


In [9]:
print(ds.coords)
print(ds.dims)

Coordinates:
    *empty*
FrozenMappingWarningOnValuesAccess({'Time': 31, 'nCells': 465044, 'nVertices': 942873})


In [10]:
print(ds)
ds.close()

<xarray.Dataset> Size: 407MB
Dimensions:                       (Time: 31, nCells: 465044, nVertices: 942873)
Dimensions without coordinates: Time, nCells, nVertices
Data variables:
    timeDaily_counter             (Time) int32 124B ...
    xtime_startDaily              (Time) |S64 2kB b'2024-12-01_00:00:00' ... ...
    xtime_endDaily                (Time) |S64 2kB ...
    timeDaily_avg_iceAreaCell     (Time, nCells) float32 58MB ...
    timeDaily_avg_iceVolumeCell   (Time, nCells) float32 58MB ...
    timeDaily_avg_snowVolumeCell  (Time, nCells) float32 58MB ...
    timeDaily_avg_uVelocityGeo    (Time, nVertices) float32 117MB ...
    timeDaily_avg_vVelocityGeo    (Time, nVertices) float32 117MB ...
Attributes: (12/490)
    case:                                                         v3.LR.histo...
    source_id:                                                    399d430113
    realm:                                                        seaIce
    product:                          

# Example of Mesh File

In [11]:
mesh = xr.open_dataset("NC_FILE_PROCESSING/mpassi.IcoswISC30E3r5.20231120.nc")

In [12]:
mesh.data_vars

Data variables:
    edgesOnEdge        (nEdges, maxEdges2) int32 68MB ...
    weightsOnEdge      (nEdges, maxEdges2) float64 135MB ...
    cellsOnEdge        (nEdges, TWO) int32 11MB ...
    verticesOnEdge     (nEdges, TWO) int32 11MB ...
    angleEdge          (nEdges) float64 11MB ...
    dcEdge             (nEdges) float64 11MB ...
    dvEdge             (nEdges) float64 11MB ...
    indexToEdgeID      (nEdges) int32 6MB ...
    latEdge            (nEdges) float64 11MB ...
    lonEdge            (nEdges) float64 11MB ...
    nEdgesOnEdge       (nEdges) int32 6MB ...
    xEdge              (nEdges) float64 11MB ...
    yEdge              (nEdges) float64 11MB ...
    zEdge              (nEdges) float64 11MB ...
    fEdge              (nEdges) float64 11MB ...
    cellsOnVertex      (nVertices, vertexDegree) int32 11MB ...
    edgesOnVertex      (nVertices, vertexDegree) int32 11MB ...
    kiteAreasOnVertex  (nVertices, vertexDegree) float64 23MB ...
    areaTriangle       (nVertices)

In [13]:
print(mesh["latCell"].attrs['long_name'])
print(mesh["lonCell"].attrs['long_name'])

Latitude location of cell centers in radians.
Longitude location of cell centers in radians.


In [14]:
cellsOnCell = mesh["cellsOnCell"].values
print(mesh["cellsOnCell"].attrs['long_name'])
print(mesh["cellsOnCell"].values)

List of cells that neighbor each cell.
[[     5      4      0      0      0      0]
 [    12     11      9      8      0      3]
 [     4     13     12      2      0      0]
 ...
 [465043      0 465040 465041      0      0]
 [     0 465042      0 465044      0      0]
 [     0      0      0      0 465043      0]]


In [15]:
print(cellsOnCell.shape[1])

6


In [16]:
print(mesh["cellsOnCell"].max().values)
print(mesh["cellsOnCell"].min().values)

465044
0


In [28]:
cellAreas = mesh["areaCell"].values
print(mesh["areaCell"].attrs['long_name'])
print(mesh["areaCell"].values)

cellAreas_units = mesh['areaCell'].attrs.get('units')
print(f"Units of area: {cellAreas_units}")

Area of each cell in the primary grid.
[7.23558958e+08 7.25959862e+08 7.24416211e+08 ... 7.85442411e+08
 7.85841763e+08 7.86602452e+08]
Units of area: m^2


In [32]:
import numpy as np

latCell = np.degrees(mesh["latCell"].values)
latitude_threshold = 40

print(latCell.shape)

mask = latCell >= latitude_threshold
print(mask.shape)
print(cellAreas.shape)

masked_cellAreas = cellAreas[mask]

square_kilometers_total = sum(masked_cellAreas) // 1e+6 # meters square converted to kilometers square

print(square_kilometers_total)

(465044,)
(465044,)
(465044,)
42069840.0


In [ ]:
#np.save('cellsOnCell.npy', cellsOnCell) 
#np.save('cellAreas.npy', cellAreas) 

In [ ]:
#landIceMask = mesh["landIceMask"].values
#np.save('landIceMask.npy', landIceMask)

In [ ]:
print(mesh.coords)
print(mesh.dims)

In [ ]:
print(mesh)

In [ ]:
mesh.close()