# Imports

In [73]:
import sys
print('System Version:', sys.version)

System Version: 3.10.18 | packaged by conda-forge | (main, Jun  4 2025, 14:45:41) [GCC 13.3.0]


In [74]:
#print(sys.executable) # for troubleshooting kernel issues
#print(sys.path)

In [75]:
import os
#print(os.getcwd())

In [76]:
import numpy as np
print('Numpy version', np.__version__)

Numpy version 2.2.6


In [77]:
import pandas as pd
print('Pandas version', pd.__version__)

Pandas version 2.3.0


In [78]:
import xarray as xr
print('Xarray version', xr.__version__)

Xarray version 2025.6.0


In [79]:
import matplotlib
import matplotlib.pyplot as plt
print('Matplotlib version', matplotlib.__version__)

Matplotlib version 3.10.3


In [80]:
import torch
from torch.utils.data import Dataset, DataLoader

print('PyTorch version', torch.__version__)

PyTorch version 2.5.1


# Hardware Details

In [81]:
print(torch.cuda.device_count()) # check the number of available CUDA devices
# will print 1 on login node; 4 on GPU exclusive node; 1 on shared GPU node

1


In [82]:
#print(torch.cuda.get_device_properties(0)) #provides information about a specific GPU

#total_memory=40326MB, multi_processor_count=108, L2_cache_size=40MB

In [83]:
import psutil
import platform

# Get general CPU information
processor_name = platform.processor()
print(f"Processor Name: {processor_name}")

# Get core counts
physical_cores = psutil.cpu_count(logical=False)
logical_cores = psutil.cpu_count(logical=True)
print(f"Physical Cores: {physical_cores}")
print(f"Logical Cores: {logical_cores}")

# Get CPU frequency
cpu_frequency = psutil.cpu_freq()
if cpu_frequency:
    print(f"Current CPU Frequency: {cpu_frequency.current:.2f} MHz")
    print(f"Min CPU Frequency: {cpu_frequency.min:.2f} MHz")
    print(f"Max CPU Frequency: {cpu_frequency.max:.2f} MHz")

# Get CPU utilization (percentage)
# The interval argument specifies the time period over which to measure CPU usage.
# Setting percpu=True gives individual core utilization.
cpu_percent_total = psutil.cpu_percent(interval=1)
print(f"Total CPU Usage: {cpu_percent_total}%")

# cpu_percent_per_core = psutil.cpu_percent(interval=1, percpu=True)
# print("CPU Usage per Core:")
# for i, percent in enumerate(cpu_percent_per_core):
#     print(f"  Core {i+1}: {percent}%")

Processor Name: x86_64
Physical Cores: 128
Logical Cores: 256
Current CPU Frequency: 2249.30 MHz
Min CPU Frequency: 1500.00 MHz
Max CPU Frequency: 2000.00 MHz
Total CPU Usage: 25.4%


# Example of one netCDF file with xarray

In [84]:
ds = xr.open_dataset("train/v3.LR.DTESTM.pm-cpu-10yr.mpassi.hist.am.timeSeriesStatsDaily.0010-01-01.nc")

In [85]:
ds.data_vars

Data variables:
    timeDaily_counter             (Time) int32 124B ...
    xtime_startDaily              (Time) |S64 2kB ...
    xtime_endDaily                (Time) |S64 2kB ...
    timeDaily_avg_iceAreaCell     (Time, nCells) float32 58MB ...
    timeDaily_avg_iceVolumeCell   (Time, nCells) float32 58MB ...
    timeDaily_avg_snowVolumeCell  (Time, nCells) float32 58MB ...
    timeDaily_avg_uVelocityGeo    (Time, nVertices) float32 117MB ...
    timeDaily_avg_vVelocityGeo    (Time, nVertices) float32 117MB ...

In [86]:
day_counter = ds["timeDaily_counter"]
day_counter.shape

(31,)

In [87]:
print(ds["xtime_startDaily"])

<xarray.DataArray 'xtime_startDaily' (Time: 31)> Size: 2kB
[31 values with dtype=|S64]
Dimensions without coordinates: Time


In [88]:
print(ds["xtime_startDaily"].values)

[b'0010-01-01_00:00:00' b'0010-01-02_00:00:00' b'0010-01-03_00:00:00'
 b'0010-01-04_00:00:00' b'0010-01-05_00:00:00' b'0010-01-06_00:00:00'
 b'0010-01-07_00:00:00' b'0010-01-08_00:00:00' b'0010-01-09_00:00:00'
 b'0010-01-10_00:00:00' b'0010-01-11_00:00:00' b'0010-01-12_00:00:00'
 b'0010-01-13_00:00:00' b'0010-01-14_00:00:00' b'0010-01-15_00:00:00'
 b'0010-01-16_00:00:00' b'0010-01-17_00:00:00' b'0010-01-18_00:00:00'
 b'0010-01-19_00:00:00' b'0010-01-20_00:00:00' b'0010-01-21_00:00:00'
 b'0010-01-22_00:00:00' b'0010-01-23_00:00:00' b'0010-01-24_00:00:00'
 b'0010-01-25_00:00:00' b'0010-01-26_00:00:00' b'0010-01-27_00:00:00'
 b'0010-01-28_00:00:00' b'0010-01-29_00:00:00' b'0010-01-30_00:00:00'
 b'0010-01-31_00:00:00']


In [89]:
ice_area = ds["timeDaily_avg_iceAreaCell"]
ice_area.shape

(31, 465044)

In [90]:
ice_area.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(31, 465044), dtype=float32)

In [91]:
print(ds.coords)
print(ds.dims)

Coordinates:
    *empty*
FrozenMappingWarningOnValuesAccess({'Time': 31, 'nCells': 465044, 'nVertices': 942873})


In [92]:
print(ds)
del ds

<xarray.Dataset> Size: 407MB
Dimensions:                       (Time: 31, nCells: 465044, nVertices: 942873)
Dimensions without coordinates: Time, nCells, nVertices
Data variables:
    timeDaily_counter             (Time) int32 124B ...
    xtime_startDaily              (Time) |S64 2kB b'0010-01-01_00:00:00' ... ...
    xtime_endDaily                (Time) |S64 2kB ...
    timeDaily_avg_iceAreaCell     (Time, nCells) float32 58MB 0.0 0.0 ... 0.0
    timeDaily_avg_iceVolumeCell   (Time, nCells) float32 58MB ...
    timeDaily_avg_snowVolumeCell  (Time, nCells) float32 58MB ...
    timeDaily_avg_uVelocityGeo    (Time, nVertices) float32 117MB ...
    timeDaily_avg_vVelocityGeo    (Time, nVertices) float32 117MB ...
Attributes: (12/490)
    case:                                                         v3.LR.DTEST...
    source_id:                                                    9741e0bba2
    realm:                                                        seaIce
    product:              

# Example of Mesh File

In [93]:
mesh = xr.open_dataset("NC_FILE_PROCESSING/mpassi.IcoswISC30E3r5.20231120.nc")

In [94]:
mesh.data_vars

Data variables:
    edgesOnEdge        (nEdges, maxEdges2) int32 68MB ...
    weightsOnEdge      (nEdges, maxEdges2) float64 135MB ...
    cellsOnEdge        (nEdges, TWO) int32 11MB ...
    verticesOnEdge     (nEdges, TWO) int32 11MB ...
    angleEdge          (nEdges) float64 11MB ...
    dcEdge             (nEdges) float64 11MB ...
    dvEdge             (nEdges) float64 11MB ...
    indexToEdgeID      (nEdges) int32 6MB ...
    latEdge            (nEdges) float64 11MB ...
    lonEdge            (nEdges) float64 11MB ...
    nEdgesOnEdge       (nEdges) int32 6MB ...
    xEdge              (nEdges) float64 11MB ...
    yEdge              (nEdges) float64 11MB ...
    zEdge              (nEdges) float64 11MB ...
    fEdge              (nEdges) float64 11MB ...
    cellsOnVertex      (nVertices, vertexDegree) int32 11MB ...
    edgesOnVertex      (nVertices, vertexDegree) int32 11MB ...
    kiteAreasOnVertex  (nVertices, vertexDegree) float64 23MB ...
    areaTriangle       (nVertices)

In [95]:
cellsOnCell = mesh["cellsOnCell"].values
print(mesh["cellsOnCell"].values)

[[     5      4      0      0      0      0]
 [    12     11      9      8      0      3]
 [     4     13     12      2      0      0]
 ...
 [465043      0 465040 465041      0      0]
 [     0 465042      0 465044      0      0]
 [     0      0      0      0 465043      0]]


In [96]:
print(mesh["cellsOnCell"].max().values)
print(mesh["cellsOnCell"].min().values)

465044
0


In [97]:
np.save('cellsOnCell.npy', cellsOnCell) 

In [98]:
print(mesh.coords)
print(mesh.dims)

Coordinates:
    *empty*
FrozenMappingWarningOnValuesAccess({'nEdges': 1408196, 'maxEdges2': 12, 'TWO': 2, 'nVertices': 942873, 'vertexDegree': 3, 'nCells': 465044, 'maxEdges': 6, 'Time': 1})


In [99]:
print(mesh)

<xarray.Dataset> Size: 509MB
Dimensions:            (nEdges: 1408196, maxEdges2: 12, TWO: 2,
                        nVertices: 942873, vertexDegree: 3, nCells: 465044,
                        maxEdges: 6, Time: 1)
Dimensions without coordinates: nEdges, maxEdges2, TWO, nVertices,
                                vertexDegree, nCells, maxEdges, Time
Data variables: (12/40)
    edgesOnEdge        (nEdges, maxEdges2) int32 68MB ...
    weightsOnEdge      (nEdges, maxEdges2) float64 135MB ...
    cellsOnEdge        (nEdges, TWO) int32 11MB ...
    verticesOnEdge     (nEdges, TWO) int32 11MB ...
    angleEdge          (nEdges) float64 11MB ...
    dcEdge             (nEdges) float64 11MB ...
    ...                 ...
    nEdgesOnCell       (nCells) int32 2MB ...
    xCell              (nCells) float64 4MB ...
    yCell              (nCells) float64 4MB ...
    zCell              (nCells) float64 4MB ...
    fCell              (nCells) float64 4MB ...
    landIceMask        (Time, nCells) 

In [100]:
del mesh

# Pre-processing + Freeboard calculation functions

In [101]:
# Constants (adjust if you use different units)
D_WATER = 1023  # Density of seawater (kg/m^3)
D_ICE = 917     # Density of sea ice (kg/m^3)
D_SNOW = 330    # Density of snow (kg/m^3)

MIN_AREA = 1e-6

def compute_freeboard(area: np.ndarray, 
                      ice_volume: np.ndarray, 
                      snow_volume: np.ndarray) -> np.ndarray:
    """
    Compute sea ice freeboard from ice and snow volume and area.
    
    Parameters
    ----------
    area : np.ndarray
        Sea ice concentration / area (same shape as ice_volume and snow_volume).
    ice_volume : np.ndarray
        Sea ice volume per grid cell.
    snow_volume : np.ndarray
        Snow volume per grid cell.
    
    Returns
    -------
    freeboard : np.ndarray
        Freeboard height for each cell, same shape as inputs.
    """
    # Initialize arrays
    height_ice = np.zeros_like(ice_volume)
    height_snow = np.zeros_like(snow_volume)

    # Valid mask: avoid dividing by very small or zero area
    valid = area > MIN_AREA

    # Safely compute heights where valid
    height_ice[valid] = ice_volume[valid] / area[valid]
    height_snow[valid] = snow_volume[valid] / area[valid]

    # Compute freeboard using the physical formula
    freeboard = (
        height_ice * (D_WATER - D_ICE) / D_WATER +
        height_snow * (D_WATER - D_SNOW) / D_WATER
    )

    return freeboard


In [102]:
def normalize_freeboard(freeboard, min_val=-0.2, max_val=1.2):
    return np.clip((freeboard - min_val) / (max_val - min_val), 0, 1)

# Custom Pytorch Dataset

Example from NERSC of using ERA5 Dataset:
https://github.com/NERSC/dl-at-scale-training/blob/main/utils/data_loader.py

## Constants

TRY: NUM_WORKERS as 16 to 32 - profile to see if the GPU is still waiting on the CPU.

TRY: NUM_WORKERS as 64 - the number of CPU cores available.

TRY: NUM_WORKERS experiment with os.cpu_count() - 2

TRY: NUM_WORKERS experiment with (logical_cores_per_gpu * num_gpus)

num_workers considerations:
Too few workers: GPUs might become idle waiting for data.
Too many workers: Can lead to increased CPU memory usage and context switching overhead.


In [103]:
NUM_WORKERS = 64
BATCH_SIZE = 16

# __ init __ - masks and loads the data into tensors

In [104]:
import os
import time
from datetime import datetime
from datetime import timedelta

from torch.utils.data import Dataset
from typing import List, Union, Callable, Tuple
from NC_FILE_PROCESSING.patchify_utils import patchify_by_latlon_spillover
from perlmutterpath import * # Contains the data_dir and mesh_dir variables

class DailyNetCDFDataset(Dataset):
    """
    PyTorch Dataset that concatenates a directory of month-wise NetCDF files
    along their 'Time' dimension and yields daily data *plus* its timestamp.

    Parameters
    ----------
    data_dir : str
        Directory containing NetCDF files
    transform : Callable | None
        Optional transform applied to the data tensor *only*.
    decode_time : bool
        Let xarray convert CF-style time coordinates to np.datetime64.
    drop_missing : bool
        If True, drops any days where one of the requested variables is missing.
    """
    def __init__(
        self,
        data_dir: str = data_dir,
        mesh_dir: str = mesh_dir,
        transform: Callable = None,
        decode_time: bool = True,
        drop_missing: bool = True,
        latitude_threshold = 40
    ):

        """ __init__ needs to 

        Handle the raw data:
        1) Gather the sorted daily data from each netCDF file (1 file = 1 month of daily data)
            The netCDF files contain nCells worth of data per day for each feature (ice area, ice volume, etc.)
            nCells = 465044 with the IcoswISC30E3r5 mesh
        2) Store the datetime information from each nCells array from the daily data
        3) Extract raw data
        
        Perform pre-processing:
        4) Apply a mask to nCells to look just at regions in certain latitudes
            nCells >= 40 degrees is 53973 cells
            nCells >= 50 degrees is 35623 cells
        5) Derive Freeboard from ice area, snow volume, and ice volume
        6) Custom patchify and store patch_ids so the data loader can use them (TODO: IMPLEMENT THIS)
        7) Concatenate the data across Time
        8) Normalize the data (Ice area is already between 0 and 1; Freeboard is not) """

        start_time = time.time()
        self.transform = transform

        # --- 1. Gather files (sorted for deterministic order) ---------
        self.data_dir = data_dir
        self.file_paths = sorted(
            [
                os.path.join(data_dir, f)
                for f in os.listdir(data_dir)
                if f.endswith(".nc")
            ]
        )
        print(f"Found {len(self.file_paths)} NetCDF files:")
        # for f in self.file_paths:
        #     print(f"  - {f}")     # Print all the file names in the folder

        if not self.file_paths:
            raise FileNotFoundError(f"No *.nc files found in {data_dir!r}")

        # Open all the netCDF files and concatenate them along Time dimension
        print("Loading datasets with xarray.open_mfdataset...")
        
        ds = xr.open_mfdataset(
            self.file_paths,
            combine="nested",
            concat_dim="Time", # Use the NetCDF's Time dimension for concatenation
            decode_times=False,
            parallel=False,
        )

        print("Finished loading full dataset into a local variable.")

        print(f"Dataset dimensions: {ds.dims}")
        print(f"Dataset variables: {list(ds.data_vars)}")
        
        # --- 2. Store a list of datetimes from each file -> helps with retrieving 1 day's data later
        all_times = []
        for path in self.file_paths:
            ds = xr.open_dataset(path)
        
            # Decode byte strings and fix the format
            xtime_strs = ds["xtime_startDaily"].str.decode("utf-8").values
            xtime_strs = [s.replace("_", " ") for s in xtime_strs]  # "0010-01-01_00:00:00" → "0010-01-01 00:00:00"
        
            # Convert to datetime.datetime objects
            times = [datetime.strptime(s, "%Y-%m-%d %H:%M:%S") for s in xtime_strs]
            all_times.extend(times)
        
        # Store in self.times
        self.times = all_times
        self.times = np.array(self.times, dtype='datetime64[s]')

        # Checking the dates
        print(f"Parsed {len(self.times)} total dates")
        print("First few:", self.times[:5])

        # Stats on how many dates there are
        print(f"Total days collected: {len(self.times)}")
        print(f"Unique days: {len(np.unique(self.times))}")
        print(f"First 35 days: {self.times[:35]}")
        print(f"First days 360 to 400 days: {self.times[360:401]}")

        # Load the mesh file. Latitudes and Longitudes are in radians.
        mesh = xr.open_dataset(mesh_dir)
        latCell = np.degrees(mesh["latCell"].values)
        lonCell = np.degrees(mesh["lonCell"].values)
        self.cell_mask = latCell >= latitude_threshold
        print("Mask size: ", np.count_nonzero(self.cell_mask))

        self.full_to_masked = {
            full_idx: new_idx
            for new_idx, full_idx in enumerate(np.where(self.cell_mask)[0])
        }

        # --- 3. Extract raw data 
        self.freeboard_all = []
        self.ice_area_all = []

        for path in self.file_paths:
            ds = xr.open_dataset(path)

            # Extract raw data
            area = ds["timeDaily_avg_iceAreaCell"].values
            ice_volume = ds["timeDaily_avg_iceVolumeCell"].values
            snow_volume = ds["timeDaily_avg_snowVolumeCell"].values

            # --- 4. Apply a mask to the nCells
            area = area[:, self.cell_mask]
            ice_volume = ice_volume[:, self.cell_mask]
            snow_volume = snow_volume[:, self.cell_mask]

            # --- 5. Derive Freeboard from ice area, snow volume and ice volume
            freeboard = compute_freeboard(area, ice_volume, snow_volume)

            # These will be deleted later to save space
            self.freeboard_all.append(freeboard) 
            self.ice_area_all.append(area)

        # --- 6. Custom patchify function       
        self.full_nCells_patch_ids, self.indices_per_patch_id = patchify_by_latlon_spillover(
            latCell, lonCell, k=256, max_patches=140, lat_threshold=latitude_threshold)


        # Convert full-domain patch indices to masked-domain indices
        self.indices_per_patch_id = [
            [self.full_to_masked[i] for i in patch if i in self.full_to_masked]
            for patch in self.indices_per_patch_id
        ]

        # --- 7. Concatenate the data across Time

        # Concatenate across time
        self.freeboard = np.concatenate(self.freeboard_all, axis=0)  # (T, nCells)
        self.ice_area = np.concatenate(self.ice_area_all, axis=0)    # (T, nCells)

        # Discard the lists that are not needed anymore -- save space
        del self.freeboard_all, self.ice_area_all

        print("Freeboard", self.freeboard.shape)
        print("Ice Area", self.ice_area.shape)

        # --- 8. Normalize the data (Area is already between 0 and 1; Freeboard is not)
        self.freeboard_min = self.freeboard[0].min()
        self.freeboard_max = self.freeboard[0].max()
        
        print("Freeboard min:", self.freeboard_min)
        print("Freeboard max:", self.freeboard_max)

        self.freeboard_all = normalize_freeboard(
            freeboard, min_val=self.freeboard_min, max_val=self.freeboard_max)

        print("=== Normalized Freeboard ===")
        
        print("End of __init__")

        end_time = time.time()
        elapsed_time = end_time - start_time
        print(f"Elapsed time: {elapsed_time} seconds")

    def __len__(self) -> int:
        """ Returns how many time steps? (Days for Daily data) """
        
        print("Calling __len__")
        return len(self.times)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, np.datetime64]:

        """__ getitem __ needs to 
        
        1. Select one time step (ex. 1 day). 
        2. Return all the patches for one time step
        Features are: [freeboard, ice_area] over masked cells. """

        start_time = time.time()
        print("Calling __getitem__")
        
        freeboard_day = self.freeboard[idx]  # shape: (nCells,)
        ice_area_day = self.ice_area[idx]    # shape: (nCells,)
        print("Freeboard shape", freeboard_day.shape)
        print("Ice Area shape", ice_area_day.shape)

        features = np.stack([freeboard_day, ice_area_day], axis=0)  # shape: (2, nCells)
        patch_tensors = []

        for patch_indices in self.indices_per_patch_id:
            patch = features[:, patch_indices]  # shape: (2, patch_size)
            patch_tensors.append(torch.tensor(patch, dtype=torch.float32))

        patch_tensor = torch.stack(patch_tensors)  # shape: (num_patches, 2, patch_size)

        if self.transform:
            patch_tensor = self.transform(patch_tensor)

        print(f"Fetched index {idx}: Time={self.times[idx]}")
        print(f"[num_patches, num_features, patch_size]={patch_tensor.size()}")

        end_time = time.time()
        elapsed_time = end_time - start_time
        print(f"Elapsed time: {elapsed_time} seconds")

        return patch_tensor, self.times[idx]  # shape: (num_patches, 2, patch_size)

    def __repr__(self):
        """ Format the string representation of the data """
        return (
            f"<DailyNetCDFDataset: {len(self)} days, "
            f"{len(self.freeboard[0])} cells/day, "
            f"{len(self.file_paths)} files loaded>"
        )

    def time_to_dataframe(self) -> pd.DataFrame:
            """Return a DataFrame of time features you can merge with predictions."""
            t = pd.to_datetime(self.times)            # pandas Timestamp index
            return pd.DataFrame(
                {
                    "time": t,
                    "year": t.year,
                    "month": t.month,
                    "day": t.day,
                    "doy": t.dayofyear,
                }
            )

# DataLoader

In [105]:
from torch.utils.data import DataLoader

print("===== Making the Dataset Class ===== ")
dataset = DailyNetCDFDataset(data_dir)

print("===== Printing Dataset ===== ")
print(dataset)                 # calls __repr__ → see how many files & days loaded
sample, ts = dataset[0]        # sample is tensor, ts is np.datetime64

# wrap in a DataLoader
# 1. use pinned memory for faster asynch transfer to GPUs)
# 2. use a prefetch factor so that the GPU is fed w/o a ton of CPU memory use
loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=False, 
                    num_workers=NUM_WORKERS, pin_memory=True, prefetch_factor=2)

# quickly get engineered time-features
# df_time = dataset.time_to_dataframe()


===== Making the Dataset Class ===== 
Found 12 NetCDF files:
Loading datasets with xarray.open_mfdataset...
Finished loading full dataset into a local variable.
Dataset dimensions: FrozenMappingWarningOnValuesAccess({'Time': 365, 'nCells': 465044, 'nVertices': 942873})
Dataset variables: ['timeDaily_counter', 'xtime_startDaily', 'xtime_endDaily', 'timeDaily_avg_iceAreaCell', 'timeDaily_avg_iceVolumeCell', 'timeDaily_avg_snowVolumeCell', 'timeDaily_avg_uVelocityGeo', 'timeDaily_avg_vVelocityGeo']
Parsed 365 total dates
First few: ['0010-01-01T00:00:00' '0010-01-02T00:00:00' '0010-01-03T00:00:00'
 '0010-01-04T00:00:00' '0010-01-05T00:00:00']
Total days collected: 365
Unique days: 365
First 35 days: ['0010-01-01T00:00:00' '0010-01-02T00:00:00' '0010-01-03T00:00:00'
 '0010-01-04T00:00:00' '0010-01-05T00:00:00' '0010-01-06T00:00:00'
 '0010-01-07T00:00:00' '0010-01-08T00:00:00' '0010-01-09T00:00:00'
 '0010-01-10T00:00:00' '0010-01-11T00:00:00' '0010-01-12T00:00:00'
 '0010-01-13T00:00:00' '00

# Transformer
<!-- outputs = model(features)
model.train()
model.eval() -->

In [106]:
# import torch
# import torch.nn as nn

# # THIS ONE IS AN OPTION FOR IF I IMPLEMENT PATCHES

# class PatchTransformer(nn.Module):
#     def __init__(self, patch_dim, num_patches, d_model=128, nhead=8, num_layers=4):
#         super().__init__()

#         print("Calling __init__")
#         start_time = time.time()
        
#         self.patch_embed = nn.Linear(patch_dim, d_model)  # input projection

#         self.pos_embed = nn.Parameter(torch.randn(1, num_patches, d_model))  # learnable positional encoding

#         encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=nhead, batch_first=True)
#         self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

#         self.mlp_head = nn.Sequential(
#             nn.LayerNorm(d_model),
#             nn.Linear(d_model, 1)  # regression or classification
#         )

#         end_time = time.time()
#         elapsed_time = end_time - start_time
#         print(f"Elapsed time: {elapsed_time} seconds")
#         print("End of __init__")

#     def forward(self, x):
#         """
#         x: (batch_size, num_patches, patch_dim)
#         """

#         print("Calling forward")
#         start_time = time.time()
        
#         x = self.patch_embed(x) + self.pos_embed
#         x = self.encoder(x)  # (batch_size, num_patches, d_model)

#         # Option 1: Mean over tokens
#         x = x.mean(dim=1)  # (batch_size, d_model)

#         # attn: shape (num_layers, num_heads, num_tokens, num_tokens)
#         attn = self.transformer(..., output_attentions=True)

#         end_time = time.time()
#         elapsed_time = end_time - start_time
#         print(f"Elapsed time: {elapsed_time} seconds")
#         print("End of __init__")

#         return self.mlp_head(x)  # output shape: (batch_size, 1)


In [107]:
# import torch.nn as nn

# class IceForecastTransformer(nn.Module):
#     def __init__(self, input_dim, model_dim, n_heads, n_layers, output_dim):
#         super().__init__()
#         self.input_proj = nn.Linear(input_dim, model_dim)
#         encoder_layer = nn.TransformerEncoderLayer(d_model=model_dim, nhead=n_heads)
#         self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=n_layers)
#         self.head = nn.Linear(model_dim, output_dim)

#     def forward(self, x):
#         # x shape: (batch, seq_len, input_dim)
#         x = self.input_proj(x)
#         x = x.permute(1, 0, 2)  # (seq_len, batch, model_dim)
#         x = self.transformer(x)
#         x = x[-1]  # use final token for prediction
#         # attn: shape (num_layers, num_heads, num_tokens, num_tokens)
#         attn = self.transformer(..., output_attentions=True)
#         return self.head(x)


In [108]:
# from torch.utils.data import DataLoader
# import torch.optim as optim

# num_epochs = 100

# model = PatchTransformer(patch_dim=2, num_patches=100)  # TODO: adjust
# optimizer = optim.Adam(model.parameters(), lr=1e-4)
# criterion = nn.MSELoss() # loss function

# # This version expects patching to be done in the Dataset
# for epoch in range(num_epochs):
#     for x, _ in loader:  # x: (B, num_patches, patch_dim)
#         y_pred = model(x)
#         loss = criterion(y_pred, targets)  # you still need to define targets

#         optimizer.zero_grad()
#         loss.backward()
#         optimizer.step()

TODO: Add Positional Encoding to represent time steps.

TODO: Use patch embedding (like in Vision Transformers).

TODO OPTION: Try temporal attention only (e.g., Informer, Time Series Transformer).

In [109]:
# Define the path where you want to save the model
PATH = "sea_ice_concentration_model.pth"

# Save the model's state_dict
torch.save(model.state_dict(), PATH)

NameError: name 'model' is not defined

# Retrieving Results

In [ ]:
# denormalizing for min-max
# original = normalized * (max_val - min_val) + min_val